-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")
-- require("bufferline").setup({
--   highlights = {
--
--     fill = {
--       bg = {
--         attribute = "fg",
--         highlight = "Pmenu",
--       },
--     },
--   },
-- })
-- require("telescope").setup({
--   extensions = {
--     aerial = {
--       -- Set the width of the first two columns (the second
--       -- is relevant only when show_columns is set to 'both')
--       col1_width = 4,
--       col2_width = 30,
--       -- How to format the symbols
--       format_symbol = function(symbol_path, filetype)
--         if filetype == "json" or filetype == "yaml" then
--           return table.concat(symbol_path, ".")
--         else
--           return symbol_path[#symbol_path]
--         end
--       end,
--       -- Available modes: symbols, lines, both
--       show_columns = "both",
--     },
--   },
-- })
-- require("telescope").load_extension("aerial")
